## Task

1. Write a NumPy program to test element-wise for NaN of a given array.
2. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
3. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
4. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
5. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
6. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
7. In the code cell below, write the code to get and display the 55th row in the dataframe df.
8. In the code cell below write the code to display the first 10 rows of the dataframe <code>df</code>.
9. In the code cell below, select and display the first eight rows from the <code>'Country'</code> and <code>'TB deaths'</code> columns.
10. In the code cell below write code to find all the rows in <code>df</code> where TB deaths exceed 10000.
11. In the code cell below find  all the countries where the Population (1000s) is **less than or equal to** 50000 **or** TB deaths are **greater than or equal to** 20000.

In [ ]:
#import module
import numpy as np

In [ ]:
#Task 1: A program to test element-wise for NaN of a given array

#array with a NaN value
arr = np.array([1, 2, np.nan, 4, np.nan, 6])
print("Original Array:")
print(arr)

#Test element-wise  for NaN
result = np.isnan(arr)
print("\nElement-wise NaN Check:")
print(result)

Original Array:
[ 1.  2. nan  4. nan  6.]

Element-wise NaN Check:
[False False  True False  True False]

In [2]:
#Task 2: A program testing element-wise for complex number, real number of a given array

#Array with different data types
arr = np.array([1, 2+3j, 4.5, 3-2j, 5])
print("Original Array:")
print(arr)

#Element-wise test for complex numbers
is_complex = np.iscomplex(arr)
print("\nElement-wise Complex Check:")
print(is_complex)

#Element-wise test for real numbers
is_real = np.isreal(arr)
print("\nElement-wise Real Check:")
print(is_real)

#Test whether scalar_num and array_num is a scalar type or not
scalar_num = 5
array_num = np.array([1, 2, 3])

is_scalar_1 = np.isscalar(scalar_num)
print("\nIs 5 a scalar?")
print(is_scalar_1)

is_scalar_2 = np.isscalar(array_num)
print("\nIs [1,2,3] a scalar?")
print(is_scalar_2)

Original Array:
[1. +0.j 2. +3.j 4.5+0.j 3. -2.j 5. +0.j]

Element-wise Complex Check:
[False  True False  True False]

Element-wise Real Check:
[ True False  True False  True]

Is 5 a scalar?
True

Is [1,2,3] a scalar?
False

In [4]:
#Task 3: A program to test whether two arrays are element-wise equal within a tolerance

#Create two arrays that are close but not equal
arr1 = np.array([1.0, 2.001, 3.0, 4.0005])
arr2 = np.array([1.0, 2.0, 3.0001, 4.0])
print("Array 1:", arr1)
print("Array 2:", arr2)

#Test if the two arrays are equal within a tolerance
result = np.allclose(arr1, arr2, atol=0.001)
print("\nAre the arrays element-wise equal within a tolerance?")
print(result)

Array 1: [1.     2.001  3.     4.0005]
Array 2: [1.     2.     3.0001 4.    ]

Are the arrays element-wise equal within a tolerance?
True

In [6]:
#Task 4: A program to create an element-wise comparison of two given arrays

#Two given arrays
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([40,50,60,60,50])
print("Array 1:", arr1)
print("Array 2:", arr2)

#A greater element-wise comparison
greater = np.greater(arr1, arr2)
print("\nElement-wise 'greater' comparison (arr1 > arr2):")
print(greater)

#A greater_equal element-wise comparison
greater_equal = np.greater_equal(arr1, arr2)
print("\nElement-wise 'greater_equal' comparison (arr1 >= arr2):")
print(greater_equal)

#A less element-wise comparison
less = np.less(arr1, arr2)
print("\nElement-wise 'less' comparison (arr1 < arr2):")
print(less)

#A less_equal element-wise comparison
less_equal = np.less_equal(arr1, arr2)
print("\nElement-wise 'less_equal' comparison (arr1 <= arr2):")
print(less_equal)

Array 1: [10 20 30 40 50]
Array 2: [40 50 60 60 50]

Element-wise 'greater' comparison (arr1 > arr2):
[False False False False False]

Element-wise 'greater_equal' comparison (arr1 >= arr2):
[False False False False  True]

Element-wise 'less' comparison (arr1 < arr2):
[ True  True  True  True False]

Element-wise 'less_equal' comparison (arr1 <= arr2):
[ True  True  True  True  True]

In [9]:
#Task 5: A program to cretae an element-wise comparison of two given arrays

#Create two arrays
arr1 = np.array([10,20,30.0001,40])
arr2 = np.array([40,50,60,60])
print("Array 1:", arr1)
print("Array 2:", arr2)

#An equal element-wise comparison
equal = np.equal(arr1, arr2)
print("\nElement-wise Exact Equality (arr1 == arr2):")
print(equal)

#An equal within a tolerance element-wise comparison
close = np.isclose(arr1, arr2, atol=20)
print("\nElement-wise Equality Within a Tolerance (|a - b| <= 20):")
print(close)

Array 1: [10.     20.     30.0001 40.    ]
Array 2: [40 50 60 60]

Element-wise Exact Equality (arr1 == arr2):
[False False False False]

Element-wise Equality Within a Tolerance (|a - b| <= 20):
[False False False  True]

In [ ]:
#Task 6: A program to create an array with the values 1,7,13,105 and determine the size of the memory occupied by the array

#An array with values 1,7,13 and 105
arr = np.array([1, 7, 13, 105])
print("Array:", arr)

#Determine memory size occupied by array
print("Total memory size (in bytes):", arr.nbytes)

Array: [  1   7  13 105]
Total memory size (in bytes): 32

#Task 7: Code to get and display the 55th row in the dataframe df.

df.iloc[54]

#Task 8: Code to get and display the first 10 rows of the dataframe df.

df.head(10)

#Task 9: Display the first eight rows from the 'Country' and 'TB deaths' columns.

df[['Country','TB deaths']].head(8)

#Task 10: Find all the rows in df where TB deaths exceed 10000

df[df['TB deaths'] > 10000]

#Task 11: Find all the countries where the Population (1000s) is less than or equal to 50000 or TB deaths are greater than or equal to 20000

df[(df['Population (1000s)'] <= 50000) | (df['TB deaths'] >= 20000)]

## Assignment

1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.


2. Write a Python program to convert a Panda module Series to Python list and it's type.


3. Write a Python program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


4. Write a Python program to get the largest integer smaller or equal to the division of the inputs.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


5. Write a Python program to convert a dictionary to a Pandas series.
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a 100
b 200
c 300
d 400
e 800
dtype: int64


6. Write a Python program to convert a NumPy array to a Pandas series.
Sample Series:
NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0 10
1 20
2 30
3 40
4 50
dtype: int64


7. Write a Python program to change the data type of given a column or a Series.
Sample Series:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Change the said data type to numeric:
0 100.00
1 200.00
2 NaN
3 300.12
4 400.00
dtype: float64


8. Write a Python Pandas program to convert the first column of a DataFrame as a Series.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
1st column as a Series:
0 1
1 2
2 3
3 4
4 7
5 11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


9. Write a Pandas program to convert a given Series to an array.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']



 
10. Write a Pandas program to convert Series of lists to one Series.
Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow
dtype: object


11. Write a Pandas program to sort a given Series.
Sample Output:
Original Data Series: 0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object


12. Write a Pandas program to add some data to an existing Series.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
0 500
1 php
dtype: object

In [20]:
#Import modules

import pandas as pd
import numpy as np

In [22]:
#Assignment 1: a program to create and display a 1-D array-like object containing an array of data

#A 1-D array-like object
arrayofData = [1,2,3]
displayData = pd.Series(arrayofData)
print(displayData)

0    1
1    2
2    3
dtype: int64

In [24]:
#Assignment 2: A program to convert a Panda module series to python list and its type

#A panda module series
seriesData = pd.Series([10,20,30,40,50])
print(seriesData)

#Converting series to list and viewing its type
python_list = seriesData.tolist()
print(python_list)

print(f"Type of coverted list: {type(python_list)}")

0    10
1    20
2    30
3    40
4    50
dtype: int64
[10, 20, 30, 40, 50]
Type of coverted list: <class 'list'>

In [25]:
#Assignment 3: A python program to add, subtract, multiply and divide two pandas series. 

#Two sample pandas series
seriesData1 = pd.Series([2,4,6,8,10])
seriesData2 = pd.Series([1,3,5,7,9])

print("\nAdd")
print(seriesData1 + seriesData2)

print("\nSubtract")
print(seriesData1 - seriesData2)

print("\nMultiply")
print(seriesData1 * seriesData2)

print("\nDivide")
print(seriesData1 / seriesData2)

Add
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtract
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiply
0     2
1    12
2    30
3    56
4    90
dtype: int64

Divide
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [26]:
#Assignment 4: A program to get the largest integer smaller or equal to the division of the inputs.

#Two sample pandas series
serieData1 = pd.Series([2,4,6,8,10])
serieData2 = pd.Series([1,3,5,7,9])

print("Floor division result:")
print(serieData1 // serieData2)

Floor division result:
0    2
1    1
2    1
3    1
4    1
dtype: int64

In [27]:
#Assignment 5: A python program to convert a dictionary to a pandas series.

#original dictionary
originalDict = {'a': 100, 'b':200, 'c': 300, 'd': 400, 'e': 800}

#convert dictionary to series
convertedSerie = pd.Series(originalDict)

print("Converted series:")
print(convertedSerie)

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64

In [28]:
#Assignment 6: A program to convert a numpy array to a pandas series

#Sample numpy array
numpyArray = np.array([10,20,30,40,50])
print("Original Numpy Array")
print(numpyArray)

#Converting a numpy array to pandas series
pandaSeries = pd.Series(numpyArray)
print("\nConverted Pandas Series")
print(pandaSeries)

Original Numpy Array
[10 20 30 40 50]

Converted Pandas Series
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [30]:
#Assignment 7: A program to change the data type of given a column or series

#Original Data Series
data = pd.Series([100, 200, 'python', 300.12, 400])
print("Original Data Series:")
print(data)

#Chnaging the data type to numeric coercing errors to NaN
numeric_data = pd.to_numeric(data, errors='coerce')
print("\nChange the said data type to numeric:")
print(numeric_data)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [31]:
#Assignment 8: a pandas program to convert the first column of a dataframe as a series

#Original Dataframe
data = {
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)

#Converting the first column to a series
firstColSeries = df.iloc[:, 0] 
print("\n1st column as a Series:")
print(firstColSeries)

print(type(firstColSeries))

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.Series'>

In [40]:
#Assignment 9: a pandas program to convert a given series to an array

#Original data series
data = pd.Series([100, 200, 'python', 300.12, 400])
print("Original Data Series:")
print(data)

#converting the original series to a numpy array
array_version = data.to_numpy()
print("\nSeries to an array:")
print(array_version)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array:
[100 200 'python' 300.12 400]

In [38]:
#Assignment 10: a pandas program to convert series of lists to one series

#Original series of list
color_series = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])

print("Original Series of list:")
print(color_series)

#Convert to one series using explode
flatSeries = color_series.explode(ignore_index=True)
print("\nOne Series:")
print(flatSeries)

Original Series of list:
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: str

In [41]:
#Assignment 11: a pandas program to sort a given series

#Original Data Series
data = pd.Series([100, 200, 'python', 300.12, 400])
print("Original Data Series:")
print(data)

#Sorting the series
sortedSeries = data.astype(str).sort_values()
print("\nSorted Data Series:")
print(sortedSeries)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted Data Series:
0       100
1       200
3    300.12
4       400
2    python
dtype: str

In [39]:
#Assignment 12: a pandas program to add some data to an existing series

#Sample data series
data = pd.Series([100, 200, 'python', 300.12, 400])
print("Original Data Series:")
print(data)

#New data to add
new_data = pd.Series([500, 'php'])

#Add the new data to sample data series using concat
updated_series = pd.concat([data, new_data])

print("\nData Series after adding some data:")
print(updated_series)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

## Assessment

#### The datasets now live in the cohort database (schema `week06`)

The six airport weather datasets are the tables:

```
week06.beijing_pek_2014, week06.brasilia_bsb_2014, week06.capetown_cpt_2014,
week06.delhi_del_2014,   week06.london_2014,       week06.moscow_svo_2014
```

Pull them with SQL and explore them — see **`Data Access (SQL).md`** in this week's folder
for the connection snippet and worked examples. For example:

```python
from db.dataraflow_db import run_query
london = run_query("SELECT * FROM week06.london_2014")
```

Run your analysis on them, and detail your findings below as much as you can.

In [2]:
#import the six airport weather dataset 
from db.dataraflow_db import run_query

beijing = run_query("SELECT * FROM week06.beijing_pek_2014")
brasilia = run_query("SELECT * FROM week06.brasilia_bsb_2014")
capetown = run_query("SELECT * FROM week06.capetown_cpt_2014")
delhi = run_query("SELECT * FROM week06.delhi_del_2014")
london = run_query("SELECT * FROM week06.london_2014")
moscow = run_query("SELECT * FROM week06.moscow_svo_2014")

In [8]:
#Overview of Beijing City Dataset
print("Beijing Dataset Overview")

#1. Show the shape
print("Shape:", beijing.shape)

#2. Show info
print(beijing.info())

Beijing Dataset Overview
Shape: (365, 23)
<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    str
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            365 non-null    int64
 14   Mean VisibilityKm           365 non-null    int64
 15   Min VisibilitykM            365 non-null    int64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          154 non-null    float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  141 non-null    float64
 21   Events                      122 non-null    str
 22  WindDirDegrees<br />         365 non-null    str
dtypes: float64(3), int64(17), str(3)
memory usage: 65.7 KB
None

In [9]:
#Overview of Brasilia City Dataset
print("Brasilia Dataset Overview")

#1. Show the shape
print("Shape:", brasilia.shape)

#2. Show info
print(brasilia.info())

Brasilia Dataset Overview
Shape: (365, 23)
<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    str
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            365 non-null    int64
 14   Mean VisibilityKm           365 non-null    int64
 15   Min VisibilitykM            365 non-null    int64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          36 non-null     float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  334 non-null    float64
 21   Events                      162 non-null    str
 22  WindDirDegrees<br />         365 non-null    str
dtypes: float64(3), int64(17), str(3)
memory usage: 65.7 KB
None

In [10]:
#Overview of Capetown City Dataset
print("Capetown Dataset Overview")

#1. Show the shape
print("Shape:", capetown.shape)

#2. Show info
print(capetown.info())

Capetown Dataset Overview
Shape: (365, 23)
<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    str
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            363 non-null    float64
 14   Mean VisibilityKm           363 non-null    float64
 15   Min VisibilitykM            363 non-null    float64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          50 non-null     float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  310 non-null    float64
 21   Events                      136 non-null    str
 22  WindDirDegrees<br />         365 non-null    str
dtypes: float64(6), int64(14), str(3)
memory usage: 65.7 KB
None

In [11]:
#Overview of Delhi City Dataset
print("Delhi Dataset Overview")

#1. Show the shape
print("Shape:", delhi.shape)

#2. Show info
print(delhi.info())

Delhi Dataset Overview
Shape: (365, 23)
<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    str
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            365 non-null    int64
 14   Mean VisibilityKm           365 non-null    int64
 15   Min VisibilitykM            365 non-null    int64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          2 non-null      float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  285 non-null    float64
 21   Events                      92 non-null     str
 22  WindDirDegrees<br />         365 non-null    str
dtypes: float64(3), int64(17), str(3)
memory usage: 65.7 KB
None

In [12]:
#Overview of London City Dataset
print("London Dataset Overview")

#1. Show the shape
print("Shape:", london.shape)

#2. Show info
print(london.info())

London Dataset Overview
Shape: (365, 23)
<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   GMT                          365 non-null    str
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            365 non-null    int64
 14   Mean VisibilityKm           365 non-null    int64
 15   Min VisibilitykM            365 non-null    int64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          131 non-null    float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  355 non-null    float64
 21   Events                      251 non-null    str
 22  WindDirDegrees<br />         365 non-null    str
dtypes: float64(3), int64(17), str(3)
memory usage: 65.7 KB
None

In [13]:
#Overview of Moscow City Dataset
print("Moscow Dataset Overview")

#1. Show the shape
print("Shape:", moscow.shape)

#2. Show info
print(moscow.info())

Moscow Dataset Overview
Shape: (365, 23)
<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    str
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            333 non-null    float64
 14   Mean VisibilityKm           333 non-null    float64
 15   Min VisibilitykM            333 non-null    float64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          213 non-null    float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  333 non-null    float64
 21   Events                      216 non-null    str
 22  WindDirDegrees<br />         365 non-null    str
dtypes: float64(6), int64(14), str(3)
memory usage: 65.7 KB
None

In [3]:
#Numerical Summary

#Displaying Beijing Statistical information
print(beijing.describe())

       Max TemperatureC  Mean TemperatureC  Min TemperatureC  Dew PointC  \
count        365.000000         365.000000        365.000000  365.000000
mean          19.523288          13.364384          7.542466    6.580822
std           11.249060          10.937703         11.032742   12.328479
min           -2.000000          -7.000000        -13.000000  -24.000000
25%            9.000000           3.000000         -3.000000   -4.000000
50%           22.000000          14.000000          9.000000    9.000000
75%           30.000000          23.000000         18.000000   18.000000
max           42.000000          31.000000         27.000000   25.000000

       MeanDew PointC  Min DewpointC  Max Humidity   Mean Humidity  \
count      365.000000     365.000000    365.000000      365.000000
mean         2.123288      -2.465753     78.630137       50.753425
std         13.762452      15.056015     18.203299       19.083953
min        -33.000000     -40.000000     19.000000        8.000000
25%         -9.000000     -14.000000     69.000000       37.000000
50%          3.000000      -2.000000     83.000000       50.000000
75%         15.000000      11.000000     94.000000       65.000000
max         24.000000      23.000000    100.000000       93.000000

        Min Humidity   Max Sea Level PressurehPa   Mean Sea Level PressurehPa  \
count     365.000000                  365.000000                   365.000000
mean       23.753425                 1019.536986                  1016.657534
std        17.474142                   10.026442                     9.641969
min         4.000000                 1001.000000                   996.000000
25%         8.000000                 1010.000000                  1008.000000
50%        20.000000                 1019.000000                  1016.000000
75%        36.000000                 1028.000000                  1025.000000
max        81.000000                 1039.000000                  1037.000000

        Min Sea Level PressurehPa   Max VisibilityKm   Mean VisibilityKm  \
count                  365.000000         365.000000          365.000000
mean                  1013.934247          18.073973            9.504110
std                      9.512055          10.124907            6.458074
min                    993.000000           2.000000            1.000000
25%                   1005.000000           8.000000            5.000000
50%                   1014.000000          18.000000            7.000000
75%                   1022.000000          31.000000           13.000000
max                   1034.000000          31.000000           31.000000

        Min VisibilitykM   Max Wind SpeedKm/h   Mean Wind SpeedKm/h  \
count         365.000000           365.000000            365.000000
mean            4.131507            21.961644              8.942466
std             3.993019            10.709894              4.651536
min             0.000000             6.000000              3.000000
25%             2.000000            14.000000              6.000000
50%             3.000000            18.000000              8.000000
75%             6.000000            26.000000             10.000000
max            31.000000            72.000000             34.000000

        Max Gust SpeedKm/h  Precipitationmm   CloudCover
count            154.00000       365.000000   141.000000
mean              43.61039         1.112027     5.624113
std               15.27025         5.510722     2.657977
min               21.00000         0.000000     1.000000
25%               32.00000         0.000000     3.000000
50%               40.00000         0.000000     7.000000
75%               50.00000         0.000000     8.000000
max               93.00000        75.950000     8.000000

In [4]:
#Displaying Brasilia Statistical information
print(brasilia.describe())

       Max TemperatureC  Mean TemperatureC  Min TemperatureC  Dew PointC  \
count        365.000000         365.000000        365.000000  365.000000
mean          28.284932          22.895890         17.726027   15.813699
std            2.324243           2.035431          2.702564    3.496203
min           19.000000          16.000000          9.000000    6.000000
25%           27.000000          21.000000         16.000000   13.000000
50%           28.000000          23.000000         18.000000   17.000000
75%           29.000000          24.000000         20.000000   19.000000
max           36.000000          28.000000         23.000000   22.000000

       MeanDew PointC  Min DewpointC  Max Humidity   Mean Humidity  \
count      365.000000     365.000000    365.000000      365.000000
mean        13.676712      10.558904     79.504110       58.068493
std          3.896974       4.949188     11.356758       13.868821
min          3.000000      -5.000000     47.000000       26.000000
25%         11.000000       7.000000     73.000000       49.000000
50%         14.000000      11.000000     83.000000       58.000000
75%         17.000000      15.000000     88.000000       70.000000
max         19.000000      18.000000    100.000000       88.000000

        Min Humidity   Max Sea Level PressurehPa   Mean Sea Level PressurehPa  \
count     365.000000                  365.000000                   365.000000
mean       29.780822                 1021.410959                  1019.219178
std        14.187952                    2.347758                     2.333738
min         6.000000                 1015.000000                  1014.000000
25%        19.000000                 1020.000000                  1018.000000
50%        27.000000                 1021.000000                  1019.000000
75%        39.000000                 1023.000000                  1020.000000
max        73.000000                 1028.000000                  1026.000000

        Min Sea Level PressurehPa   Max VisibilityKm   Mean VisibilityKm  \
count                  365.000000         365.000000          365.000000
mean                  1017.016438          18.975342           12.265753
std                      2.523462           0.471082            2.459128
min                   1012.000000          10.000000            7.000000
25%                   1015.000000          19.000000           11.000000
50%                   1017.000000          19.000000           12.000000
75%                   1018.000000          19.000000           13.000000
max                   1025.000000          19.000000           19.000000

        Min VisibilitykM   Max Wind SpeedKm/h   Mean Wind SpeedKm/h  \
count         365.000000           365.000000            365.000000
mean            8.780822            22.364384              7.632877
std             4.389193            11.227730              2.659632
min             0.000000            10.000000              3.000000
25%             6.000000            19.000000              6.000000
50%            10.000000            21.000000              8.000000
75%            10.000000            24.000000             10.000000
max            19.000000           195.000000             19.000000

        Max Gust SpeedKm/h  Precipitationmm   CloudCover
count            36.000000       365.000000   334.000000
mean             43.444444         2.059315     3.523952
std               9.012513         6.186198     1.312115
min              26.000000         0.000000     1.000000
25%              39.000000         0.000000     3.000000
50%              41.000000         0.000000     3.000000
75%              52.000000         0.760000     5.000000
max              66.000000        57.910000     7.000000

In [5]:
#Displaying Capetown Statistical information
print(capetown.describe())

       Max TemperatureC  Mean TemperatureC  Min TemperatureC  Dew PointC  \
count        365.000000         365.000000        365.000000  365.000000
mean          22.684932          17.567123         12.509589   13.783562
std            4.839957           4.148880          4.288118    3.018215
min           11.000000           7.000000          1.000000    5.000000
25%           19.000000          14.000000          9.000000   12.000000
50%           23.000000          18.000000         13.000000   14.000000
75%           26.000000          21.000000         16.000000   16.000000
max           37.000000          28.000000         22.000000   21.000000

       MeanDew PointC  Min DewpointC  Max Humidity   Mean Humidity  \
count      365.000000     365.000000    365.000000      365.000000
mean        11.583562       9.134247     87.452055       68.758904
std          3.289469       3.892943      7.311817        8.740581
min          2.000000      -2.000000     63.000000       42.000000
25%          9.000000       6.000000     82.000000       62.000000
50%         12.000000       9.000000     88.000000       69.000000
75%         14.000000      12.000000     94.000000       76.000000
max         20.000000      18.000000    100.000000       88.000000

        Min Humidity   Max Sea Level PressurehPa   Mean Sea Level PressurehPa  \
count     365.000000                  365.000000                   365.000000
mean       42.150685                 1019.347945                  1016.654795
std        12.762918                    5.428054                     5.220549
min         0.000000                 1006.000000                  1004.000000
25%        34.000000                 1016.000000                  1013.000000
50%        42.000000                 1019.000000                  1016.000000
75%        50.000000                 1022.000000                  1020.000000
max        78.000000                 1036.000000                  1034.000000

        Min Sea Level PressurehPa   Max VisibilityKm   Mean VisibilityKm  \
count                  365.000000         363.000000          363.000000
mean                  1014.232877          27.325069           14.468320
std                      5.284023           4.696196            4.397509
min                   1002.000000          10.000000            6.000000
25%                   1010.000000          26.000000           12.000000
50%                   1014.000000          31.000000           13.000000
75%                   1017.000000          31.000000           16.000000
max                   1033.000000          31.000000           31.000000

        Min VisibilitykM   Max Wind SpeedKm/h   Mean Wind SpeedKm/h  \
count         363.000000           365.000000            365.000000
mean            8.650138            31.090411             16.934247
std             5.022207            10.294031              7.334703
min             0.000000            11.000000              5.000000
25%             6.000000            23.000000             11.000000
50%            10.000000            32.000000             16.000000
75%            10.000000            39.000000             21.000000
max            31.000000            58.000000             43.000000

        Max Gust SpeedKm/h  Precipitationmm   CloudCover
count            50.000000       365.000000   310.000000
mean             55.600000         1.173288     3.087097
std              10.006121         4.503512     1.790526
min              34.000000         0.000000     1.000000
25%              48.000000         0.000000     1.000000
50%              56.500000         0.000000     3.000000
75%              63.000000         0.000000     5.000000
max              76.000000        59.940000     7.000000

In [6]:
#Displaying Delhi Statistical information
print(delhi.describe())

       Max TemperatureC  Mean TemperatureC  Min TemperatureC  Dew PointC  \
count        365.000000         365.000000        365.000000  365.000000
mean          20.200000          13.709589          7.197260    6.443836
std           11.521409          10.060151          8.855339    6.440364
min           -6.000000         -11.000000        -17.000000  -13.000000
25%           11.000000           6.000000          1.000000    2.000000
50%           21.000000          14.000000          8.000000    8.000000
75%           31.000000          23.000000         15.000000   12.000000
max           38.000000          30.000000         23.000000   18.000000

       MeanDew PointC  Min DewpointC  Max Humidity   Mean Humidity  \
count      365.000000     365.000000    365.000000      365.000000
mean         3.783562       0.506849     74.813699       50.638356
std          6.511170       6.703950     16.751688       18.401077
min        -15.000000     -22.000000     30.000000       16.000000
25%         -1.000000      -4.000000     60.000000       35.000000
50%          4.000000       1.000000     78.000000       49.000000
75%          9.000000       6.000000     88.000000       65.000000
max         16.000000      13.000000    100.000000       94.000000

        Min Humidity   Max Sea Level PressurehPa   Mean Sea Level PressurehPa  \
count     365.000000                  365.000000                   365.000000
mean       27.410959                 1019.200000                  1015.200000
std        18.439264                    7.746038                     8.261921
min         4.000000                 1000.000000                   997.000000
25%        14.000000                 1014.000000                  1009.000000
50%        21.000000                 1017.000000                  1014.000000
75%        38.000000                 1025.000000                  1021.000000
max        84.000000                 1042.000000                  1036.000000

        Min Sea Level PressurehPa   Max VisibilityKm   Mean VisibilityKm  \
count                  365.000000         365.000000          365.000000
mean                  1010.920548          11.575342            9.512329
std                      9.486355           2.833851            2.098662
min                    991.000000           2.000000            2.000000
25%                   1003.000000          10.000000            9.000000
50%                   1010.000000          11.000000           10.000000
75%                   1018.000000          14.000000           11.000000
max                   1035.000000          19.000000           14.000000

        Min VisibilitykM   Max Wind SpeedKm/h   Mean Wind SpeedKm/h  \
count         365.000000           365.000000            365.000000
mean            8.202740            19.265753              5.915068
std             3.022351            14.916362              4.449462
min             0.000000             0.000000              0.000000
25%             8.000000            11.000000              3.000000
50%            10.000000            18.000000              5.000000
75%            10.000000            23.000000              6.000000
max            10.000000           209.000000             37.000000

        Max Gust SpeedKm/h  Precipitationmm   CloudCover
count             2.000000       365.000000   285.000000
mean             47.500000         0.617288     3.508772
std               7.778175         1.772568     2.610399
min              42.000000         0.000000     0.000000
25%              44.750000         0.000000     1.000000
50%              47.500000         0.000000     3.000000
75%              50.250000         0.000000     6.000000
max              53.000000        11.940000     8.000000

In [7]:
#Displaying London Statistical information
print(london.describe())

       Max TemperatureC  Mean TemperatureC  Min TemperatureC  Dew PointC  \
count        365.000000         365.000000        365.000000  365.000000
mean          16.328767          12.328767          8.293151   10.356164
std            5.766174           5.087300          4.773908    3.835096
min            4.000000           1.000000         -4.000000    1.000000
25%           11.000000           8.000000          5.000000    8.000000
50%           16.000000          12.000000          8.000000   11.000000
75%           21.000000          17.000000         12.000000   13.000000
max           30.000000          24.000000         19.000000   19.000000

       MeanDew PointC  Min DewpointC  Max Humidity   Mean Humidity  \
count      365.000000     365.000000    365.000000      365.000000
mean         7.863014       5.241096     93.145205       73.802740
std          3.929024       4.177643      5.685267       10.379317
min         -2.000000      -6.000000     71.000000       48.000000
25%          4.000000       2.000000     88.000000       66.000000
50%          8.000000       5.000000     94.000000       74.000000
75%         11.000000       8.000000    100.000000       82.000000
max         17.000000      15.000000    100.000000       96.000000

        Min Humidity   Max Sea Level PressurehPa   Mean Sea Level PressurehPa  \
count     365.000000                  365.000000                   365.000000
mean       47.019178                 1015.980822                  1012.386301
std        16.107201                    9.523087                    10.393432
min        15.000000                  987.000000                   979.000000
25%        34.000000                 1011.000000                  1006.000000
50%        45.000000                 1016.000000                  1013.000000
75%        60.000000                 1023.000000                  1020.000000
max        92.000000                 1043.000000                  1041.000000

        Min Sea Level PressurehPa   Max VisibilityKm   Mean VisibilityKm  \
count                  365.000000         365.000000          365.000000
mean                  1008.994521          28.808219           13.167123
std                     11.424861           4.842740            3.339246
min                    975.000000           6.000000            3.000000
25%                   1002.000000          29.000000           11.000000
50%                   1011.000000          31.000000           13.000000
75%                   1017.000000          31.000000           15.000000
max                   1038.000000          31.000000           24.000000

        Min VisibilitykM   Max Wind SpeedKm/h   Mean Wind SpeedKm/h  \
count         365.000000           365.000000            365.000000
mean            6.183562            25.175342             13.863014
std             3.255047             9.238414              6.374561
min             0.000000             8.000000              3.000000
25%             3.000000            19.000000             10.000000
50%             6.000000            24.000000             13.000000
75%            10.000000            29.000000             16.000000
max            10.000000            66.000000             47.000000

        Max Gust SpeedKm/h  Precipitationmm   CloudCover
count           131.000000       365.000000   355.000000
mean             47.541985         1.378356     3.177465
std              11.514045         3.097608     1.433872
min              27.000000         0.000000     1.000000
25%              39.000000         0.000000     2.000000
50%              47.000000         0.000000     3.000000
75%              53.000000         1.020000     4.000000
max              90.000000        21.080000     7.000000

In [8]:
#Displaying Moscow Statistical information
print(moscow.describe())

       Max TemperatureC  Mean TemperatureC  Min TemperatureC  Dew PointC  \
count        365.000000         365.000000        365.000000  365.000000
mean          10.334247           5.994521          2.063014    3.621918
std           12.195210          10.724829          9.657536    9.114025
min          -19.000000         -21.000000        -26.000000  -24.000000
25%            1.000000          -1.000000         -4.000000   -3.000000
50%            9.000000           6.000000          2.000000    4.000000
75%           21.000000          14.000000         10.000000   12.000000
max           33.000000          26.000000         19.000000   20.000000

       MeanDew PointC  Min DewpointC  Max Humidity   Mean Humidity  \
count      365.000000     365.000000    365.000000      365.000000
mean         1.104110      -1.580822     91.301370       73.378082
std          9.163659       9.464054      9.824679       15.895765
min        -26.000000     -29.000000     54.000000       40.000000
25%         -6.000000      -8.000000     87.000000       61.000000
50%          2.000000      -1.000000     93.000000       76.000000
75%          9.000000       7.000000    100.000000       87.000000
max         18.000000      15.000000    100.000000      100.000000

        Min Humidity   Max Sea Level PressurehPa   Mean Sea Level PressurehPa  \
count     365.000000                  365.000000                   365.000000
mean       55.939726                 1019.723288                  1017.112329
std        21.494867                    9.774526                    10.445357
min        16.000000                  981.000000                   974.000000
25%        37.000000                 1014.000000                  1011.000000
50%        54.000000                 1019.000000                  1017.000000
75%        75.000000                 1026.000000                  1023.000000
max        93.000000                 1053.000000                  1053.000000

        Min Sea Level PressurehPa   Max VisibilityKm   Mean VisibilityKm  \
count                  365.000000         333.000000          333.000000
mean                  1014.454795           9.537538            8.291291
std                     10.945231           1.218310            2.073023
min                    970.000000           3.000000            1.000000
25%                   1008.000000          10.000000            7.000000
50%                   1015.000000          10.000000            9.000000
75%                   1021.000000          10.000000           10.000000
max                   1052.000000          10.000000           10.000000

        Min VisibilitykM   Max Wind SpeedKm/h   Mean Wind SpeedKm/h  \
count         333.000000           365.000000            365.000000
mean            5.819820            22.863014             12.835616
std             3.304428             6.787017              4.949785
min             0.000000             6.000000              2.000000
25%             3.000000            18.000000             10.000000
50%             6.000000            21.000000             13.000000
75%             9.000000            29.000000             16.000000
max            10.000000            47.000000             27.000000

        Max Gust SpeedKm/h  Precipitationmm   CloudCover
count           213.000000            365.0   333.000000
mean             40.065728              0.0     5.930931
std               8.382675              0.0     1.935256
min              21.000000              0.0     0.000000
25%              35.000000              0.0     5.000000
50%              40.000000              0.0     6.000000
75%              47.000000              0.0     7.000000
max              72.000000              0.0     8.000000

In [12]:
#Checking the weather events in Beijing

#Check events column while counting the number of times a weather appeared and ensures missing values are displayed
print(beijing[' Events'].value_counts(dropna=False))

 Events
NaN                      243
Rain                      44
Rain-Thunderstorm         33
Fog                       28
Snow                       7
Fog-Rain                   5
Fog-Snow                   2
Fog-Rain-Thunderstorm      2
Thunderstorm               1
Name: count, dtype: int64

In [13]:
#Checking the weather events in Brasilia

#Check events column while counting the number of times a weather appeared and ensures missing values are displayed
print(brasilia[' Events'].value_counts(dropna=False))

 Events
NaN                       203
Rain-Thunderstorm          75
Rain                       41
Thunderstorm               30
Fog-Rain-Thunderstorm       6
Fog                         6
Fog-Thunderstorm            2
Fog-Rain                    1
Rain-Hail-Thunderstorm      1
Name: count, dtype: int64

In [14]:
#Checking the weather events in Capetown

#Check events column while counting the number of times a weather appeared and ensures missing values are displayed
print(capetown[' Events'].value_counts(dropna=False))

 Events
NaN                  229
Rain                  87
Fog                   38
Fog-Rain               8
Rain-Thunderstorm      2
Rain-Snow              1
Name: count, dtype: int64

In [15]:
#Checking the weather events in Delhi

#Check events column while counting the number of times a weather appeared and ensures missing values are displayed
print(delhi[' Events'].value_counts(dropna=False))

 Events
NaN                  273
Rain                  51
Thunderstorm          13
Snow                   8
Rain-Thunderstorm      8
Fog                    5
Rain-Snow              5
Hail-Thunderstorm      1
Fog-Snow               1
Name: count, dtype: int64

In [16]:
#Checking the weather events in London

#Check events column while counting the number of times a weather appeared and ensures missing values are displayed
print(london[' Events'].value_counts(dropna=False))

 Events
Rain                          202
NaN                           114
Fog-Rain                       17
Rain-Thunderstorm              15
Fog                            13
Fog-Rain-Thunderstorm           2
Rain-Snow                       1
Fog-Rain-Snow-Thunderstorm      1
Name: count, dtype: int64

In [17]:
#Checking the weather events in Moscow

#Check events column while counting the number of times a weather appeared and ensures missing values are displayed
print(moscow[' Events'].value_counts(dropna=False))

 Events
NaN                      149
Snow                      73
Rain                      70
Fog                       18
Rain-Thunderstorm         16
Rain-Snow                 15
Fog-Rain                   9
Fog-Snow                   6
Thunderstorm               5
Fog-Rain-Snow              3
Fog-Rain-Thunderstorm      1
Name: count, dtype: int64

# Assessment Findings

1. The dataset contains daily airport weather entries for six cities; Beijing, Brasilia, Cape Town, Delhi, London and Moscow. Each dataset contain for 365 rows and 23 columns. 

2. Drastic missing data were found in 'Max Gust SpeedKm/h', 'CloudCover' and 'Events' which is across all cities.

3. There were trailing spaces and HTML remnants in several column headings.

4. London had an inconsistent column unlike other cities e.g GMT instead of Date.

5. Rain is the most recorded event in most cities.

6. Most of the cities contains NaN values in the Events columns meaning that the event in most days wasn't recorded or the weather were calm and cool.

7. Brasilia recorded 75 Rain-Thunderstorm days with 203 NaN values.

8. London has the highest number of rainy days (202) in 2014.

9. Moscow records 73 snow days and 70 rainy days.

---
## SQL Assessment (Intermediate SQL)

This part tests what you learnt in **`4-Intermediate SQL/Intermediate SQL.ipynb`**. Every task runs against the
**live cohort database** using your **read-only** account.

**How it works**
1. Run the **SQL setup** cell below first (and again after restarting the kernel).
2. In each task cell, write your query **between the triple quotes**, then run the cell.
3. `answer(...)` runs your query, shows the result, and tells you if it's ✅ correct. If not, it tells you
   whether the **shape** (rows × columns) is right, so you know where to look.
4. Match the **column order**, **sort order** and **rounding** asked for. Column *names* aren't checked,
   but use the names given.
5. Run `sql_score()` at the end to see your SQL score.

Writes are blocked: the database is read-only, so build everything inside your `SELECT` (CTEs are your workspace).

In [1]:
# --- SQL setup: run this cell first (don't edit it) ---
import sys, pathlib, re, json, hashlib, datetime, math
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query
import pandas as pd

_BLOCKED = re.compile(r"\b(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|CREATE|TRUNCATE|EXEC|EXECUTE|GRANT|REVOKE|DENY|INTO|BACKUP|RESTORE)\b", re.I)

def _strip(sql):
    sql = re.sub(r"'([^']|'')*'", "''", sql)
    sql = re.sub(r"--[^\n]*", "", sql)
    return re.sub(r"/\*.*?\*/", "", sql, flags=re.S)

def q(sql):
    """Run a read-only query and return a DataFrame (same helper as the Intermediate SQL notebook)."""
    hit = _BLOCKED.search(_strip(sql))
    if hit:
        raise PermissionError(f"'{hit.group(0).upper()}' is not allowed: the database is read-only.")
    return run_query(sql)

_DATE = re.compile(r"^\d{4}-\d{1,2}-\d{1,2}")

def _norm(v):
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return None
    if isinstance(v, (datetime.date, datetime.datetime, pd.Timestamp)):
        return pd.Timestamp(v).date().isoformat()
    if isinstance(v, str):
        v = v.strip()
        if _DATE.match(v):
            try:
                return pd.Timestamp(v).date().isoformat()
            except ValueError:
                pass
        return v
    try:
        return round(float(v), 2)
    except (TypeError, ValueError):
        return str(v)

def _fingerprint(df):
    rows = [[_norm(v) for v in row] for row in df.itertuples(index=False)]
    return hashlib.sha256(json.dumps(rows).encode()).hexdigest()

# expected answers are stored only as fingerprints, so this notebook doesn't give them away
EXPECTED = {
 "s01": [
  [
   8,
   2
  ],
  "0ba3b4c0210bb324982933cd308c7ff0bb3fbbea32fc6646d9e9e2a9bb14df70"
 ],
 "s02": [
  [
   1,
   3
  ],
  "1512ef1d7254b2206516b1f4bb9dea659b456cab8b80402f5bf67de186fc7fff"
 ],
 "s03": [
  [
   3,
   4
  ],
  "607a2a3b80c9fdc820855d34f48730b445d9437842569c3d7406962b2ec71409"
 ],
 "s04": [
  [
   26,
   2
  ],
  "2fe50527877da0fd0064e1512aa038aa08109668d30b5e0083874edc03b773cf"
 ],
 "s05": [
  [
   5,
   2
  ],
  "8d5b93be4960cbb6acd605b1fa741b3be8bbe6c44c5fb19b843daf38737e1ab1"
 ],
 "s06": [
  [
   1,
   1
  ],
  "c3c32ce95ec239c2ac639584925dced87cfb17b11bee9b738bc7ed104c2ce931"
 ],
 "s07": [
  [
   6,
   2
  ],
  "8450a870c23b5bfab2a420e0a10a1b534e113a7c4acd0be5b90060f8bebe4e2c"
 ],
 "s08": [
  [
   12,
   3
  ],
  "27236391b69c4478be3e09fa08b89fe7c5acd46b03bb5a934c14e6e122bddb0d"
 ],
 "s09": [
  [
   12,
   3
  ],
  "880e60a4b694da3e224b104c67139870b74671f6ef86f16b9d5ac46c2d81ad04"
 ],
 "s10": [
  [
   3,
   4
  ],
  "9b15fac9c91f6a72150b0c1705f96f0e8281cbe86e49c56d49f37a3d885328ac"
 ]
}
TASKS = {
 "s01": "Exploring the schema",
 "s02": "Filtering & NULLs",
 "s03": "CASE & conditional aggregation",
 "s04": "GROUP BY + HAVING",
 "s05": "JOIN across sources",
 "s06": "Anti-join",
 "s07": "UNION ALL",
 "s08": "CTE + window ranking",
 "s09": "Running total (window)",
 "s10": "Business question"
}
RESULTS = {}

def answer(task, sql):
    """Run your query for a task, show the result, and check it."""
    shape, fp = EXPECTED[task]
    if not _strip(sql).strip():
        RESULTS[task] = None
        print(f"⏳ {task}: not attempted yet. Write your query between the triple quotes.")
        return
    try:
        df = q(sql)
    except Exception as err:
        RESULTS[task] = False
        print(f"❌ {task}: the query failed.\n   {type(err).__name__}: {str(err)[:300]}")
        return
    display(df.head(15))
    ok = _fingerprint(df) == fp
    RESULTS[task] = ok
    if ok:
        print(f"✅ {task}: correct!")
        return
    print(f"❌ {task}: not quite. Expected {shape[0]} row(s) × {shape[1]} column(s); "
          f"you returned {df.shape[0]} × {df.shape[1]}.")
    if df.shape == tuple(shape):
        print("   The shape is right, so check: column order, sort order, rounding, and filters "
              "(NULLs, the 'World' row, etc.).")

def sql_score():
    """Print your SQL score table."""
    rows = []
    for task, title in TASKS.items():
        r = RESULTS.get(task)
        rows.append([task, title, "✅" if r else ("not attempted" if r is None else "❌")])
    table = pd.DataFrame(rows, columns=["Task", "Topic", "Result"])
    print(table.to_string(index=False))
    print(f"\nSQL score: {sum(1 for r in RESULTS.values() if r)} / {len(TASKS)}")

print(f"SQL setup done: {len(TASKS)} tasks. Connected as:",
      run_query("SELECT CURRENT_USER AS u").u[0])

SQL setup done: 10 tasks. Connected as: intern_readonly

### SQL Task 1 · Exploring the schema
Using `INFORMATION_SCHEMA.COLUMNS`, list every table in the **`week06`** schema with **how many columns** it has.

**Return:** `table_name`, `n_columns`, sorted by `table_name` (A→Z).
*Revisit: Intermediate SQL §1.*

In [3]:
SQL_01 = """
    SELECT TABLE_NAME AS table_name, COUNT(*) AS n_columns
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'week06'
    GROUP BY table_name
    ORDER BY table_name
"""
answer("s01", SQL_01)

          table_name  n_columns
0   beijing_pek_2014         23
1  brasilia_bsb_2014         23
2  capetown_cpt_2014         23
3     delhi_del_2014         23
4        london_2014         23
5    moscow_svo_2014         23
6     who_pop_tb_all          3
7    who_pop_tb_some          3

✅ s01: correct!

### SQL Task 2 · Filtering & NULLs
For **London** (`week06.london_2014`), return **one row** with three counts:
1. `no_event_days`: days with **no event recorded**
2. `rain_days`: days whose event mentions **Rain** anywhere (e.g. `Rain`, `Fog-Rain`, `Rain-Thunderstorm`)
3. `wet_but_no_event_days`: days with **no event recorded** but `Precipitationmm > 0`

⚠️ The events column name starts with a **space**: `[ Events]`. And remember, `= NULL` never matches.
*Revisit: §1.2, §3.2, §3.3.*

In [ ]:
SQL_02 = """
        SELECT
            SUM((CASE WHEN ([ EVENTS] IS NULL) THEN 1 ELSE 0 END)) AS no_event_days,
            SUM((CASE WHEN ([ Events] LIKE '%Rain%') THEN 1 ELSE 0 END)) AS rain_days,
            SUM((CASE WHEN ([ Events] IS NULL) AND (Precipitationmm > 0) THEN 1 ELSE 0 END)) AS wet_but_no_event_days

        FROM week06.london_2014
"""
answer("s02", SQL_02)

   no_event_days  rain_days  wet_but_no_event_days
0            114        238                      6

✅ s02: correct!

### SQL Task 3 · CASE & conditional aggregation
From `week16.customer_churn_prediction`, for each `Contract_Type` return: number of `customers`, number
`churned` (`Churn = 1`), and `churn_rate_pct` (percentage, **rounded to 1 decimal place**).

**Return:** `Contract_Type`, `customers`, `churned`, `churn_rate_pct`, sorted by `churn_rate_pct` (highest first).
⚠️ Watch out for the integer-division trap. *Revisit: §4.4, §5.2.*

In [5]:
SQL_03 = """
SELECT Contract_Type, COUNT(*) AS customers, SUM(churn) AS churned, ROUND(((SUM(churn) * 100.0) / COUNT(*)), 1) churn_rate_pct

FROM week16.customer_churn_prediction
GROUP BY Contract_Type
ORDER BY churn_rate_pct DESC
"""
answer("s03", SQL_03)

    Contract_Type  customers  churned  churn_rate_pct
0  Month-to-Month        158       91            57.6
1        One Year        165       89            53.9
2        Two Year        177       48            27.1

✅ s03: correct!

### SQL Task 4 · GROUP BY + HAVING
From `week09.comtrade_milk_uk_monthly_14`, find the partner countries the UK **exported** milk to in
**all 12 months** of 2014, with the **total export value**.

**Return:** `Partner`, `total_exports_usd`, sorted by `total_exports_usd` (highest first).
⚠️ Exclude the `'World'` total row. *Revisit: §6.2.*

In [6]:
SQL_04 = """
        SELECT Partner, SUM([Trade Value (US$)]) AS total_exports_usd
        FROM week09.comtrade_milk_uk_monthly_14
        WHERE partner != 'World' and [Trade Flow] = 'Exports'
        GROUP BY Partner
        HAVING COUNT(DISTINCT Period) = 12
        ORDER BY total_exports_usd DESC
"""
answer("s04", SQL_04)

                 Partner  total_exports_usd
0                Ireland          421228441
1                Algeria           93753841
2            Netherlands           68649082
3                Germany           36096633
4                 France           34622982
5                Belgium           29343007
6                  China           27317861
7   China, Hong Kong SAR           19847947
8                Nigeria           12932371
9                 Guinea           12018176
10               Lebanon           10400613
11                 Congo            6407358
12                 Spain            3548528
13  United Arab Emirates            3264368
14               Denmark            2908457

✅ s04: correct!

### SQL Task 5 · JOIN across two sources
Join WHO TB data (`week06.who_pop_tb_all`) with World Bank population (`week08.wb_pop_2013`) on the country
name. Compute **TB deaths per 100,000 people** using the **World Bank** population (`[SP.POP.TOTL]`),
**rounded to 1 decimal place**.

**Return:** the **top 5** countries: `Country`, `tb_deaths_per_100k`, highest first.
*Revisit: §7.2–7.3.*

In [7]:
SQL_05 = """
 SELECT TOP 5 tb.Country, ROUND(([TB deaths] * 100000) / [SP.POP.TOTL], 1) AS tb_deaths_per_100k
FROM week06.who_pop_tb_all tb
JOIN week08.wb_pop_2013  wb
    ON tb.country = wb.Country
ORDER BY tb_deaths_per_100k DESC
"""
answer("s05", SQL_05)

       Country  tb_deaths_per_100k
0     Djibouti               100.6
1      Nigeria                92.6
2    Swaziland                88.0
3  Timor-Leste                83.9
4      Somalia                75.0

✅ s05: correct!

### SQL Task 6 · Anti-join
How many WHO countries in `week06.who_pop_tb_all` have **no matching country name** in `week08.wb_pop_2013`?

**Return:** one row, one column (`who_countries_without_wb_match`).
*Revisit: §7.4. Bonus thought: why do these countries fail to match?*

In [8]:
SQL_06 = """
SELECT COUNT(*)
FROM week06.who_pop_tb_all tb
left JOIN week08.wb_pop_2013  wb
    ON tb.country = wb.Country
WHERE wb.Country IS NULL
"""
answer("s06", SQL_06)

0  28

✅ s06: correct!

### SQL Task 7 · UNION ALL
Stack the **six** city weather tables in `week06` and compute each city's **average `Mean TemperatureC`**
for 2014, **rounded to 1 decimal place**. Use exactly these city labels:
`'Beijing'`, `'Brasilia'`, `'Cape Town'`, `'Delhi'`, `'London'`, `'Moscow'`.

**Return:** `city`, `avg_mean_temp_c`, sorted by `city` (A→Z).
⚠️ `Mean TemperatureC` is stored as a whole number, so watch the integer-division trap. *Revisit: §8.1–8.2.*

In [9]:
# Query the six different cities' table names

run_query("""
        SELECT TABLE_SCHEMA + '.' + TABLE_NAME
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'week06'
""")

0   week06.beijing_pek_2014
1  week06.brasilia_bsb_2014
2  week06.capetown_cpt_2014
3     week06.delhi_del_2014
4        week06.london_2014
5    week06.moscow_svo_2014
6     week06.who_pop_tb_all
7    week06.who_pop_tb_some

In [10]:
SQL_07 = """
SELECT city, ROUND(AVG(CAST(mean_temp_c AS FLOAT)), 1) AS avg_mean_temp_c
FROM(
        SELECT 'Beijing' AS city,     [Mean TemperatureC] AS mean_temp_c FROM week06.beijing_pek_2014
        UNION ALL SELECT 'Brasilia',  [Mean TemperatureC] FROM week06.brasilia_bsb_2014
        UNION ALL SELECT 'Cape Town', [Mean TemperatureC] FROM week06.capetown_cpt_2014
        UNION ALL SELECT 'Delhi',     [Mean TemperatureC] FROM week06.delhi_del_2014
        UNION ALL SELECT 'London',    [Mean TemperatureC] FROM week06.london_2014
        UNION ALL SELECT 'Moscow',    [Mean TemperatureC] FROM week06.moscow_svo_2014
) AS combined_weather
GROUP BY city
ORDER BY city                                
"""
answer("s07", SQL_07)

        city  avg_mean_temp_c
0    Beijing             13.4
1   Brasilia             22.9
2  Cape Town             17.6
3      Delhi             13.7
4     London             12.3
5     Moscow              6.0

✅ s07: correct!

### SQL Task 8 · CTE + window ranking (top-1 per group)
For **London**, find the **hottest day of each month** (highest `Max TemperatureC`). If two days tie,
take the **earlier** date.

**Return:** `month_no`, `day` (a real **date**, convert `GMT` with `TRY_CONVERT(date, GMT)`), `max_temp`,
sorted by `month_no`. *Revisit: §10, §11.3.*

In [11]:
SQL_08 = """
WITH RankedTemperatures AS (
    SELECT
        TRY_CONVERT(date, GMT) AS day,
        MONTH(TRY_CONVERT(date, GMT)) AS month_no,
        [Max TemperatureC] AS max_temp,
        ROW_NUMBER() OVER (
            PARTITION BY MONTH(TRY_CONVERT(date, GMT))
            ORDER BY [Max TemperatureC] DESC, TRY_CONVERT(date, GMT) ASC
        ) AS rn
    FROM week06.london_2014
)
SELECT
    month_no,
    day,
    max_temp
FROM RankedTemperatures
WHERE rn = 1
ORDER BY month_no;
"""
answer("s08", SQL_08)

    month_no         day  max_temp
0          1  2014-01-05        12
1          2  2014-02-24        14
2          3  2014-03-09        19
3          4  2014-04-01        19
4          5  2014-05-19        26
5          6  2014-06-09        26
6          7  2014-07-18        30
7          8  2014-08-06        26
8          9  2014-09-18        26
9         10  2014-10-31        23
10        11  2014-11-01        18
11        12  2014-12-17        13

✅ s08: correct!

### SQL Task 9 · Running total
From `week09.comtrade_milk_uk_monthly_14`, compute the UK's **total milk exports per month** (exclude `'World'`)
and a **year-to-date running total**.

**Return:** `Period`, `exports_usd`, `ytd_exports_usd`, sorted by `Period`. *Revisit: §11.4–11.5.*

In [12]:
SQL_09 = """
WITH MonthlyExports AS (
    SELECT
        Period,
        SUM([Trade Value (US$)]) AS exports_usd
    FROM week09.comtrade_milk_uk_monthly_14
    WHERE partner != 'World'
      AND [Trade Flow] = 'Exports'
    GROUP BY Period
)

SELECT
    Period,
    exports_usd,
    SUM(exports_usd) OVER (ORDER BY Period) AS ytd_exports_usd
FROM MonthlyExports
ORDER BY Period
"""
answer("s09", SQL_09)

    Period  exports_usd  ytd_exports_usd
0   201401     87138654         87138654
1   201402     72489716        159628370
2   201403     86781424        246409794
3   201404     95195778        341605572
4   201405     96201135        437806707
5   201406     99315900        537122607
6   201407     72878716        610001323
7   201408     61737703        671739026
8   201409     60600293        732339319
9   201410     57003417        789342736
10  201411     49293958        838636694
11  201412     60015241        898651935

✅ s09: correct!

### SQL Task 10 · Business question
The Head of Credit asks: *"How does the approval rate vary by property area and credit history?"*
Using `week17.loan_approval_prediction`, return one row per `Property_Area` × `Credit_History` combination
that exists in the data, with the number of `applications` and the `approval_rate_pct` (rounded to 1 decimal).

**Return:** `Property_Area`, `Credit_History`, `applications`, `approval_rate_pct`, sorted by `Property_Area`
then `Credit_History`. Then answer reflection question 3 below about what you see.

In [13]:
SQL_10 = """
SELECT
    Property_Area,
    Credit_History,
    COUNT(*) AS applications,
    ROUND((SUM(CAST(Loan_Approved AS FLOAT)) * 100) / COUNT(*), 1) AS approval_rate_pct
FROM week17.loan_approval_prediction
GROUP BY Property_Area, Credit_History
ORDER BY Property_Area, Credit_History
"""
answer("s10", SQL_10)

  Property_Area  Credit_History  applications  approval_rate_pct
0         Rural               0           166                0.0
1     Semiurban               1           167              100.0
2         Urban               1           167              100.0

✅ s10: correct!

### SQL reflection
Answer in the cell below (2–3 sentences each):

1. In Task 3 or Task 7, what would `AVG(Churn)` or `AVG([Mean TemperatureC])` return **without** converting to a
   decimal first, and why?
2. In Task 6, why do those countries fail to match? How would you fix this in a real project?
3. Look at your Task 10 result. What is **suspicious** about it? What would you tell the Head of Credit before
   anyone trains a model on this data?

**My answers:**

1. *…*
2. *…*
3. *…*

### SQL score
Run this when you're done.

In [14]:
sql_score()

Task                          Topic Result
 s01           Exploring the schema      ✅
 s02              Filtering & NULLs      ✅
 s03 CASE & conditional aggregation      ✅
 s04              GROUP BY + HAVING      ✅
 s05            JOIN across sources      ✅
 s06                      Anti-join      ✅
 s07                      UNION ALL      ✅
 s08           CTE + window ranking      ✅
 s09         Running total (window)      ✅
 s10              Business question      ✅

SQL score: 10 / 10

---
## 📰 Article Link

Write a **detailed article** about this week's work. It should cover:

- **What you learnt:** the key concepts, tools and techniques from this week.
- **What you solved:** the tasks and projects you worked on, and how you approached them.
- **Challenges you faced:** what was hard, confusing or didn't work at first.
- **How you overcame them:** what you tried, what finally worked, and what you'd do differently.
- **Anything else you want to share:** insights, results, visuals, or advice for others learning this.

Publish it, then paste the article's **URL** in the empty cell below (double-click the cell to edit it).